using api.dto;
using api.utils;
using grpc;
using Microsoft.AspNetCore.Mvc;
using Via.Dk;

namespace api;

[ApiController]
[Route("api/[controller]")]
public class IngredientsController : ControllerBase
{
    private readonly GrpcClient _grpcService;

    public IngredientsController(GrpcClient grpcService)
    {
        _grpcService = grpcService;
    }

    [HttpPost]
    public async Task<IResult> CreateIngredient([FromBody] CreateIngredientRequest ingredient)
    {
        string response = await this._grpcService.IngredientsClient.CreateIngredientAsync(ingredient);
        if (response.Contains("FAIL"))
        {
            return Results.BadRequest();
        }

        return Results.Ok("Ingredient created");
    }

    [HttpPut()]
    // [HttpPut("{id:int}")]
    public async Task<IResult> UpdateIngredient([FromBody] UpdateIngredientDto ingredient)
    {
        var request = new UpdateIngredientRequest()
        {
            Id = ingredient.Id,
            Name = ingredient.Name,
            Calories = ingredient.Calories,
            IsAllergen = ingredient.IsAllergen,
        };
        string response = await this._grpcService.IngredientsClient.UpdateIngredientAsync(request);
        if (response.Contains("FAIL"))
        {
            return Results.BadRequest();
        }

        return Results.Ok("Ingredient updated");
    }

    [HttpDelete()]
    // [HttpDelete("{id:int}")]
    public async Task<IResult> DeleteIngredient([FromBody] DeleteIngredientRequest ingredient)
    {
        string response =  await this._grpcService.IngredientsClient.DeleteIngredientAsync(ingredient);
        if (response.Contains("FAIL"))
        {
            return Results.BadRequest();
        }

        return Results.Ok("Ingredient deleted");
    }
    
    [HttpGet]
    //ingredient is auto generated by grpc, might cause issues in the future
    public async Task<IResult> GetAllIngredients()
    {
        List<Ingredient> ingredients = (await _grpcService.IngredientsClient.GetAllIngredientsAsync()).ToList();
        if (ingredients.Count == 0)
        {
            return Results.NoContent();
        }
        
        return Results.Ok(ingredients);
    }
}