using grpc;
using Microsoft.AspNetCore.Mvc;
using Via.Dk;

namespace api;

[ApiController]
[Route("api/[controller]")]
public class RecipeController : ControllerBase
{
    private readonly GrpcClient _grpcService;

    public RecipeController(GrpcClient grpcService)
    {
        _grpcService = grpcService;
    }

    [HttpGet("allRecipes")]
    //the Recipe class is auto generated by the proto file and idk if this can cause problems in the future
    public async Task<IResult> GetRecipes()
    {
        List<Recipe> recipes = (await _grpcService.GetAllRecipes()).ToList();
        if (recipes.Count == 0)
        {
            return Results.NotFound("No recipes exist");
        }
        
        return Results.Ok(recipes);
    }
}